### ISSUE TITLE
How'd you even parse their tweets

### ISSUE THREAD

**Issue by alalfakawma** [essymizo/covid19-Mizoram#1]
Did you do it manually or? Really wish we could access a formatted version of the data from the official sites.

**Comment by essymizo** [comment]
Thanks ! Tweepy leh Twitter API hmangin DIPR tweets ka parse a, chuan ka duh angin ka process. Mahse an tweet ho format an hmang lo lutuk a, ka rest rih

**Comment by alalfakawma** [comment]
Nihchu. Ni ve reng. Format pangai deuh chu nei se keipawh visualization vel tih a chakawm ka tia, graph a website vela display turin, kalo ngaihtuah mai2 a. Anyways, good job!
